let city = "Hà Nội";
let number = 10;
let price = 20.5;
let status = true;
document.write("number = " + number);
document.write("<br>");
document.write("price = " + price);
document.write("<br>");
document.write("status = " + status);
document.write("<br>");
document.write("city = " + city);